openapi: 3.0.1
info:
  title: Описание API Статистики
  version: '2.18'
  description: 'Методы статистики <br><b>Лимит по запросам:</b> один запрос одного
    метода в минуту. <br><br> <a href="../../excel_save/ru/index.html">Инструкция:
    Сохранение статистики в Excel</a>

    '
security:
- HeaderApiKey: []
x-tagGroups:
- name: Статистика
  tags:
  - Статистика
tags:
- name: Статистика
components:
  securitySchemes:
    HeaderApiKey:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    responseErrorStatistics:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
    Response429:
      type: object
      properties:
        code:
          description: ''
          type: integer
        message:
          description: ''
          type: string
    IncomesItem:
      type: object
      properties:
        incomeId:
          type: integer
          description: Номер поставки
        number:
          type: string
          maxLength: 40
          description: Номер УПД
        date:
          type: string
          format: date
          description: Дата поступления. Если часовой пояс не указан, то берется Московское
            время UTC+3.
        lastChangeDate:
          type: string
          format: date-time
          description: Дата и время обновления информации в сервисе. Это поле соответствует
            параметру `dateFrom` в запросе. Если часовой пояс не указан, то берется
            Московское время UTC+3.
        supplierArticle:
          type: string
          maxLength: 75
          description: Артикул продавца
        techSize:
          type: string
          maxLength: 30
          description: Размер товара (пример S, M, L, XL, 42, 42-43)
        barcode:
          type: string
          maxLength: 30
          description: Бар-код
        quantity:
          type: integer
          description: Количество
        totalPrice:
          type: number
          description: Цена из УПД
        dateClose:
          type: string
          format: date
          description: Дата принятия (закрытия) в WB. Если часовой пояс не указан,
            то берется Московское время UTC+3.
        warehouseName:
          type: string
          maxLength: 50
          description: Название склада
        nmId:
          type: integer
          description: Артикул WB
        status:
          type: string
          maxLength: 50
          enum:
          - Принято
          description: Текущий статус поставки
    StocksItem:
      type: object
      properties:
        lastChangeDate:
          type: string
          format: date-time
          description: Дата и время обновления информации в сервисе. Это поле соответствует
            параметру `dateFrom` в запросе. Если часовой пояс не указан, то берется
            Московское время (UTC+3).
        warehouseName:
          type: string
          maxLength: 50
          description: Название склада
        supplierArticle:
          type: string
          maxLength: 75
          description: Артикул продавца
        nmId:
          type: integer
          description: Артикул WB
        barcode:
          type: string
          maxLength: 30
          description: Баркод
        quantity:
          type: integer
          description: Количество, доступное для продажи (сколько можно добавить в
            корзину)
        inWayToClient:
          type: integer
          description: В пути к клиенту
        inWayFromClient:
          type: integer
          description: В пути от клиента
        quantityFull:
          type: integer
          description: Полное (непроданное) количество, которое числится за складом
            (= `quantity` + в пути)
        category:
          type: string
          maxLength: 50
          description: Категория
        subject:
          type: string
          maxLength: 50
          description: Предмет
        brand:
          type: string
          maxLength: 50
          description: Бренд
        techSize:
          type: string
          maxLength: 30
          description: Размер
        Price:
          type: number
          description: Цена
        Discount:
          type: number
          description: Скидка
        isSupply:
          type: boolean
          description: Договор поставки (внутренние технологические данные)
        isRealization:
          type: boolean
          description: Договор реализации (внутренние технологические данные)
        SCCode:
          type: string
          maxLength: 50
          description: Код контракта (внутренние технологические данные)
    OrdersItem:
      type: object
      properties:
        gNumber:
          type: string
          maxLength: 50
          description: Номер заказа. Объединяет все позиции одного заказа.
        date:
          type: string
          format: date-time
          description: Дата и время заказа. Это поле соответствует параметру `dateFrom`
            в запросе, если параметр `flag=1`. Если часовой пояс не указан, то берется
            Московское время UTC+3.
        lastChangeDate:
          type: string
          format: date-time
          description: Дата и время обновления информации в сервисе. Это поле соответствует
            параметру `dateFrom` в запросе, если параметр `flag=0` или не указан.
            Если часовой пояс не указан, то берется Московское время UTC+3.
        supplierArticle:
          type: string
          maxLength: 75
          description: Артикул продавца
        techSize:
          type: string
          maxLength: 30
          description: Размер товара (пример S, M, L, XL, 42, 42-43)
        barcode:
          type: string
          maxLength: 30
          description: Бар-код
        totalPrice:
          type: number
          description: Цена до согласованной итоговой скидки/промо/спп. Для получения
            цены со скидкой можно воспользоваться формулой `priceWithDiscount = totalPrice
            * (1 - discountPercent/100)`
        discountPercent:
          type: integer
          description: Согласованный итоговый дисконт. Будучи примененным к `totalPrice`,
            даёт сумму к оплате.
        warehouseName:
          type: string
          maxLength: 50
          description: Название склада отгрузки
        oblast:
          type: string
          maxLength: 200
          description: Область
        incomeID:
          type: integer
          description: Номер поставки (от продавца на склад)
        odid:
          type: integer
          description: Уникальный идентификатор позиции заказа. Может использоваться
            для поиска соответствия между заказами и продажами.
        nmId:
          type: integer
          description: Артикул WB
        subject:
          type: string
          maxLength: 50
          description: Предмет
        category:
          type: string
          maxLength: 50
          description: Категория
        brand:
          type: string
          maxLength: 50
          description: Бренд
        isCancel:
          type: boolean
          description: Отмена заказа. true - заказ отменен до оплаты.
        cancel_dt:
          type: string
          format: date-time
          description: Дата и время отмены заказа. Если заказ не был отменен, то `"0001-01-01T00:00:00"`.
            Если часовой пояс не указан, то берется Московское время UTC+3.
        sticker:
          type: string
          description: Цифровое значение стикера, который клеится на товар в процессе
            сборки заказа по системе Маркетплейс.
        srid:
          type: string
          description: 'Уникальный идентификатор заказа.<br> Примечание для использующих
            API Marketplace: `srid` равен `rid` в ответах методов сборочных заданий.

            '
        orderType:
          type: string
          description: "Тип поступившего заказа <br> <dl> <dt>Возможные значения:</dt>\
            \ <dd>Клиентский - \"Заказ, поступивший от покупателя.\"</dd> <dd>Возврат\
            \ Брака - \"Возврат товара продавцу.\"</dd> <dd>Принудительный возврат\
            \ - \"Возврат товара продавцу.\"</dd> <dd>Возврат обезлички - \"Возврат\
            \ товара продавцу.\"</dd> <dd>Возврат Неверного Вложения - \"Возврат товара\
            \ продавцу.\"</dd> <dd>Возврат Продавца - \"Возврат товара продавцу.\"\
            </dd> </dl>  \n"
    SalesItem:
      type: object
      properties:
        date:
          type: string
          format: date-time
          description: Дата и время продажи. Это поле соответствует параметру `dateFrom`
            в запросе, если параметр `flag`=1. Если часовой пояс не указан, то берется
            Московское время (UTC+3).
        lastChangeDate:
          type: string
          format: date-time
          description: Дата и время обновления информации в сервисе. Это поле соответствует
            параметру `dateFrom` в запросе, если параметр `flag`=0 или не указан.
            Если часовой пояс не указан, то берется Московское время (UTC+3).
        warehouseName:
          type: string
          maxLength: 50
          description: Склад отгрузки
        countryName:
          type: string
          maxLength: 200
          description: Страна
        oblastOkrugName:
          type: string
          maxLength: 200
          description: Округ
        regionName:
          type: string
          maxLength: 200
          description: Регион
        supplierArticle:
          type: string
          maxLength: 75
          description: Артикул продавца
        nmId:
          type: integer
          description: Артикул WB
        barcode:
          type: string
          maxLength: 30
          description: Баркод
        category:
          type: string
          maxLength: 50
          description: Категория
        subject:
          type: string
          maxLength: 50
          description: Предмет
        brand:
          type: string
          maxLength: 50
          description: Бренд
        techSize:
          type: string
          maxLength: 30
          description: Размер товара
        incomeID:
          type: integer
          description: Номер поставки
        isSupply:
          type: boolean
          description: Договор поставки
        isRealization:
          type: boolean
          description: Договор реализации
        totalPrice:
          type: number
          description: Цена без скидок
        discountPercent:
          type: integer
          description: Скидка продавца
        spp:
          type: number
          description: Скидка WB
        forPay:
          type: number
          description: К перечислению продавцу
        finishedPrice:
          type: number
          description: Фактическая цена с учетом всех скидок (к взиманию с покупателя)
        priceWithDisc:
          type: number
          description: Цена со скидкой продавца, от которой считается сумма к перечислению
            продавцу `forPay` (= `totalPrice` * (1 - `discountPercent`/100))
        saleID:
          type: string
          maxLength: 15
          description: 'Уникальный идентификатор продажи/возврата <ul>  <li> `S**********`
            — продажа  <li> `R**********` — возврат (на склад WB)  </ul>

            '
        orderType:
          type: string
          description: 'Тип заказа <ul> <li> `Клиентский` — заказ, поступивший от
            покупателя <li> `Возврат Брака` — возврат товара продавцу <li> `Принудительный
            возврат` — возврат товара продавцу <li> `Возврат обезлички` — возврат
            товара продавцу <li> `Возврат Неверного Вложения` — возврат товара продавцу
            <li> `Возврат Продавца` — возврат товара продавцу </ul>

            '
        sticker:
          type: string
          description: Идентификатор стикера
        gNumber:
          type: string
          maxLength: 50
          description: Номер заказа
        odid:
          type: integer
          description: Уникальный идентификатор заказа
        srid:
          type: string
          description: 'Уникальный идентификатор заказа.<br> Примечание для использующих
            API Маркетплейс: `srid` равен `rid` в ответах методов сборочных заданий.

            '
    DetailReportItem:
      type: object
      properties:
        realizationreport_id:
          example: 1234567
          type: integer
          description: Номер отчёта
        date_from:
          example: '2022-10-17T00:00:00Z'
          type: string
          format: date-time
          description: Дата начала отчётного периода
        date_to:
          example: '2022-10-23T00:00:00Z'
          type: string
          format: date-time
          description: Дата конца отчётного периода
        create_dt:
          example: '2022-10-24T14:40:32'
          type: string
          format: date-time
          description: Дата формирования отчёта
        currency_name:
          example: руб
          type: string
          description: Валюта отчёта  <span class="new">new</span>
        suppliercontract_code:
          example: null
          type: object
          description: Договор
        rrd_id:
          example: 1232610467
          type: integer
          description: Номер строки
        gi_id:
          example: 123456
          type: integer
          description: Номер поставки
        subject_name:
          example: Мини-печи
          type: string
          description: Предмет
        nm_id:
          example: 1234567
          type: integer
          description: Артикул WB
        brand_name:
          example: BlahBlah
          type: string
          description: Бренд
        sa_name:
          example: MAB123
          type: string
          description: Артикул продавца
        ts_name:
          example: '0'
          type: string
          description: Размер
        barcode:
          example: '1231312352310'
          type: string
          description: Баркод
        doc_type_name:
          example: Продажа
          type: string
          description: Тип документа
        quantity:
          type: integer
          example: 1
          description: Количество
        retail_price:
          example: 1249
          type: number
          description: Цена розничная
        retail_amount:
          example: 367
          type: number
          description: Сумма продаж (возвратов)
        sale_percent:
          example: 68
          type: integer
          description: Согласованная скидка
        commission_percent:
          example: 0.1324
          type: number
          description: Процент комиссии
        office_name:
          example: Коледино
          type: string
          description: Склад
        supplier_oper_name:
          example: Продажа
          type: string
          description: Обоснование для оплаты
        order_dt:
          example: '2022-10-13T00:00:00Z'
          type: string
          format: date-time
          description: Дата заказа. <br> Присылается с явным указанием часового пояса
        sale_dt:
          example: '2022-10-20T00:00:00Z'
          type: string
          format: date-time
          description: Дата продажи. <br> Присылается с явным указанием часового пояса
        rr_dt:
          example: '2022-10-20T00:00:00Z'
          type: string
          format: date-time
          description: Дата операции. <br> Присылается с явным указанием часового
            пояса
        shk_id:
          example: 1239159661
          type: integer
          description: Штрих-код
        retail_price_withdisc_rub:
          example: 399.68
          type: number
          description: Цена розничная с учетом согласованной скидки
        delivery_amount:
          example: 0
          type: integer
          description: Количество доставок
        return_amount:
          example: 0
          type: integer
          description: Количество возвратов
        delivery_rub:
          example: 0
          type: number
          description: Стоимость логистики
        gi_box_type_name:
          example: Монопалета
          type: string
          description: Тип коробов
        product_discount_for_report:
          example: 399.68
          type: number
          description: Согласованный продуктовый дисконт
        supplier_promo:
          example: 0
          type: number
          description: Промокод
        rid:
          example: 123722249253
          type: integer
          description: Уникальный идентификатор заказа
        ppvz_spp_prc:
          example: 0.1581
          type: number
          description: Скидка постоянного покупателя
        ppvz_kvw_prc_base:
          example: 0.15
          type: number
          description: Размер кВВ без НДС, % базовый
        ppvz_kvw_prc:
          example: -0.0081
          type: number
          description: Итоговый кВВ без НДС, %
        sup_rating_prc_up:
          type: number
          description: Размер снижения кВВ из-за рейтинга
        is_kgvp_v2:
          type: number
          description: Размер снижения кВВ из-за акции
        ppvz_sales_commission:
          example: -3.74
          type: number
          description: Вознаграждение с продаж до вычета услуг поверенного, без НДС
        ppvz_for_pay:
          example: 376.99
          type: number
          description: К перечислению продавцу за реализованный товар
        ppvz_reward:
          example: 0
          type: number
          description: Возмещение за выдачу и возврат товаров на ПВЗ
        acquiring_fee:
          example: 14.89
          type: number
          description: 'Возмещение издержек по эквайрингу. <br> Издержки WB за услуги
            эквайринга: вычитаются из вознаграждения WB и не влияют на доход продавца.

            '
        acquiring_bank:
          example: Тинькофф
          type: string
          description: Наименование банка-эквайера
        ppvz_vw:
          example: -3.74
          type: number
          description: Вознаграждение WB без НДС
        ppvz_vw_nds:
          example: -0.75
          type: number
          description: НДС с вознаграждения WB
        ppvz_office_id:
          example: 105383
          type: integer
          description: Номер офиса
        ppvz_office_name:
          example: Пункт самовывоза (ПВЗ)
          type: string
          description: Наименование офиса доставки
        ppvz_supplier_id:
          example: 186465
          type: integer
          description: Номер партнера
        ppvz_supplier_name:
          example: ИП Жасмин
          type: string
          description: Партнер
        ppvz_inn:
          example: '010101010101'
          type: string
          description: ИНН партнера
        declaration_number:
          example: ''
          type: string
          description: Номер таможенной декларации
        bonus_type_name:
          example: Штраф МП. Невыполненный заказ (отмена клиентом после недовоза)
          type: string
          description: 'Обоснование штрафов и доплат. <br> Поле будет в ответе при
            наличии значения

            '
        sticker_id:
          example: '1964038895'
          type: string
          description: Цифровое значение стикера, который клеится на товар в процессе
            сборки заказа по схеме "Маркетплейс"
        site_country:
          example: RU
          type: string
          description: Страна продажи
        penalty:
          example: 231.35
          type: number
          description: Штрафы
        additional_payment:
          example: 0
          type: number
          description: Доплаты
        rebill_logistic_cost:
          example: 1.349
          type: number
          description: 'Возмещение издержек по перевозке. Поле будет в ответе при
            наличии значения

            '
        rebill_logistic_org:
          example: ИП Иванов Иван Иванович(123456789012)
          type: string
          description: "Организатор перевозки. Поле будет в ответе при наличии значения.\
            \          \n"
        kiz:
          example: "0102900000376311210G2CIS?ehge)S\x1D91002A\x1D92F9Qof4FDo/31Icm14kmtuVYQzLypxm3HWkC1vQ/+pVVjm1dNAth1laFMoAGn7yEMWlTjxIe7lQnJqZ7TRZhlHQ=="
          type: string
          description: 'Код маркировки. <br> Поле будет в ответе при наличии значения

            '
        srid:
          example: 711ab8cb94e040f98b3804e5f331bf7a_r
          type: string
          description: 'Уникальный идентификатор заказа. Примечание для использующих
            API Marketplace: `srid` равен `rid` в ответах методов сборочных заданий.'
  parameters:
    flag:
      in: query
      name: flag
      schema:
        type: integer
        default: 0
      required: false
      description: 'Если параметр `flag=0` (или не указан в строке запроса), при вызове
        API возвращаются данные,  у которых значение поля `lastChangeDate` (дата время
        обновления информации в сервисе) больше или равно переданному  значению параметра
        `dateFrom`.  При этом количество возвращенных строк данных варьируется в интервале
        от 0 до примерно 100 000. <br> Если параметр `flag=1`, то будет выгружена
        информация обо всех заказах или продажах с датой,  равной переданному параметру
        `dateFrom` (в данном случае время в дате значения не имеет).  При этом количество
        возвращенных строк данных будет равно количеству всех заказов или продаж,  сделанных
        в указанную дату, переданную в параметре `dateFrom`.

        '
  examples:
    TokenMissing:
      description: Токен отсутствует
      value: 'proxy: unauthorized'
    TokenInvalid:
      description: Токен недействителен
      value: 'proxy: invalid token'
    TokenNotFound:
      description: Токен удален
      value: 'proxy: not found'
    TokenIsNotApplicable:
      description: Используемый токен не применим к данным методам.
      value: 'Error ae394f96-e258-432d-af13-a53a3d31f8b0: request rejected, unathorized:
        token scope not allowed for this API route'
    CantParseDateFrom:
      description: Ошибка в запросе
      value:
        errors:
        - can't parse dateFrom
    RequestTimeout:
      description: Тайм-аут запроса
      value:
        errors:
        - (api-new) request timeout
    RequestLimitStatistics:
      description: Превышено допустимое кол-во запросов в единицу времени
      value:
        code: 429
        message: error text
paths:
  /api/v1/supplier/incomes:
    servers:
    - url: https://statistics-api.wildberries.ru
    get:
      security:
      - HeaderApiKey: []
      summary: Поставки
      description: Поставки.
      tags:
      - Статистика
      parameters:
      - name: dateFrom
        in: query
        schema:
          type: string
          format: RFC3339
        required: true
        description: 'Дата и время последнего изменения по поставке. <br> Дата в формате
          RFC3339. Можно передать дату или дату со временем.  Время можно указывать
          с точностью до секунд или миллисекунд. <br> Литера `Z` в конце строки означает,
          что время передается в UTC-часовом поясе. <br> При ее отсутствии время считается
          в часовом поясе Мск (UTC+3). <br>Примеры: <ul> <li> `2019-06-20` <li> `2019-06-20T00:00:00Z`
          <li> `2019-06-20T23:59:59` <li> `2019-06-20T00:00:00.12345Z` <li> `2019-06-20T00:00:00.12345`
          <li> `2017-03-25T00:00:00` </ul>

          '
      responses:
        200:
          description: Список поставок
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IncomesItem'
              example:
              - incomeId: 12345
                number: ''
                date: '2022-05-08T00:00:54'
                lastChangeDate: '2022-05-08T00:44:15.5'
                supplierArticle: ABCDEF
                techSize: '0'
                barcode: '2000328074123'
                quantity: 3
                totalPrice: 0
                dateClose: '2022-05-08T00:00:00'
                warehouseName: Подольск
                nmId: 1234567
                status: Принято
        401:
          description: Не авторизован
          content:
            application/json:
              schema:
                type: string
              examples:
                TokenMissing:
                  $ref: '#/components/examples/TokenMissing'
                TokenInvalid:
                  $ref: '#/components/examples/TokenInvalid'
                TokenIsNotApplicable:
                  $ref: '#/components/examples/TokenIsNotApplicable'
                TokenNotFound:
                  $ref: '#/components/examples/TokenNotFound'
        429:
          description: Слишком много запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response429'
              examples:
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
  /api/v1/supplier/stocks:
    servers:
    - url: https://statistics-api.wildberries.ru/
    get:
      security:
      - HeaderApiKey: []
      summary: Склад
      description: 'Остатки товаров на складах WB. Данные обновляются раз в 30 минут.
        <br> Сервис статистики не хранит историю остатков товаров, поэтому получить
        данные о них можно только в режиме "на текущий момент".

        '
      tags:
      - Статистика
      parameters:
      - name: dateFrom
        in: query
        schema:
          type: string
          format: RFC3339
        required: true
        description: 'Дата и время последнего изменения по товару. <br> Для получения
          полного остатка следует указывать максимально раннее значение. <br> Например,
          `2019-06-20` <br> Дата в формате RFC3339. Можно передать дату или дату со
          временем.  Время можно указывать с точностью до секунд или миллисекунд.
          <br> Литера `Z` в конце строки означает, что время передается в UTC-часовом
          поясе. <br> При ее отсутствии время считается в часовом поясе Мск (UTC+3).
          <br>Примеры: <ul> <li> `2019-06-20` <li> `2019-06-20T00:00:00Z` <li> `2019-06-20T23:59:59`
          <li> `2019-06-20T00:00:00.12345Z` <li> `2019-06-20T00:00:00.12345` <li>
          `2017-03-25T00:00:00` </ul>

          '
      responses:
        200:
          description: Список товаров на складе
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StocksItem'
              example:
              - lastChangeDate: '2023-07-05T11:13:35'
                warehouseName: Краснодар
                supplierArticle: '443284'
                nmId: 1439871458
                barcode: '2037401340280'
                quantity: 33
                inWayToClient: 1
                inWayFromClient: 0
                quantityFull: 34
                category: Посуда и инвентарь
                subject: Формы для запекания
                brand: X
                techSize: '0'
                Price: 185
                Discount: 0
                isSupply: true
                isRealization: false
                SCCode: Tech
        401:
          description: Не авторизован
          content:
            application/json:
              schema:
                type: string
              examples:
                TokenMissing:
                  $ref: '#/components/examples/TokenMissing'
                TokenInvalid:
                  $ref: '#/components/examples/TokenInvalid'
                TokenIsNotApplicable:
                  $ref: '#/components/examples/TokenIsNotApplicable'
                TokenNotFound:
                  $ref: '#/components/examples/TokenNotFound'
        429:
          description: Слишком много запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response429'
              examples:
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
  /api/v1/supplier/orders:
    servers:
    - url: https://statistics-api.wildberries.ru/
    get:
      security:
      - HeaderApiKey: []
      summary: Заказы
      description: 'Заказы. <br>  Важно: гарантируется хранение данных по заказам
        не более 90 дней от даты заказа. Данные обновляются раз в 30 минут.  Точное
        время обновления информации в сервисе можно увидеть в поле `lastChangeDate`.
        <br> Для идентификации товаров из одного заказа, а также продаж по ним, следует
        использовать  поле `gNumber` (строки с одинаковым значением этого поля относятся
        к одному заказу) и номер  уникальной позиции в заказе `odid` (`rid`).

        '
      tags:
      - Статистика
      parameters:
      - name: dateFrom
        in: query
        schema:
          type: string
          format: RFC3339
        required: true
        description: 'Дата и время последнего изменения по заказу. <br> Дата в формате
          RFC3339. Можно передать дату или дату со временем.  Время можно указывать
          с точностью до секунд или миллисекунд. <br> Литера `Z` в конце строки означает,
          что время передается в UTC-часовом поясе. <br> При ее отсутствии время считается
          в часовом поясе Мск (UTC+3). <br>Примеры: <ul> <li> `2019-06-20` <li> `2019-06-20T00:00:00Z`
          <li> `2019-06-20T23:59:59` <li> `2019-06-20T00:00:00.12345Z` <li> `2019-06-20T00:00:00.12345`
          <li> `2017-03-25T00:00:00` </ul>

          '
      - $ref: '#/components/parameters/flag'
      responses:
        200:
          description: Список заказов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrdersItem'
              example:
              - date: '2022-03-02T14:34:05'
                lastChangeDate: '2022-03-02T19:30:16'
                supplierArticle: '12345'
                techSize: '0'
                barcode: '9990016520011'
                totalPrice: 120.56
                discountPercent: 0
                warehouseName: Екатеринбург
                oblast: Московская
                incomeID: 123456
                odid: 12345678
                nmId: 12345678
                subject: Респираторы
                category: Спецодежда и СИЗы
                brand: wildberries
                isCancel: false
                cancel_dt: '0001-01-01T00:00:00'
                gNumber: '12345678'
                sticker: ''
                orderType: Клиентский
        400:
          description: Ошибка в запросе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseErrorStatistics'
              examples:
                CantParseDateFrom:
                  $ref: '#/components/examples/CantParseDateFrom'
        401:
          description: Не авторизован
          content:
            application/json:
              schema:
                type: string
              examples:
                TokenMissing:
                  $ref: '#/components/examples/TokenMissing'
                TokenInvalid:
                  $ref: '#/components/examples/TokenInvalid'
                TokenIsNotApplicable:
                  $ref: '#/components/examples/TokenIsNotApplicable'
                TokenNotFound:
                  $ref: '#/components/examples/TokenNotFound'
        429:
          description: Слишком много запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response429'
              examples:
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
  /api/v1/supplier/sales:
    servers:
    - url: https://statistics-api.wildberries.ru/
    get:
      security:
      - HeaderApiKey: []
      summary: Продажи
      description: 'Продажи и возвраты. <br> Гарантируется хранение данных не более
        90 дней от даты продажи. <br> Данные обновляются раз в 30 минут. <br> Для
        идентификации заказа следует использовать поле `srid`. <br> 1 строка = 1 продажа/возврат
        = 1 единица товара.  <br>

        '
      tags:
      - Статистика
      parameters:
      - name: dateFrom
        in: query
        schema:
          type: string
          format: RFC3339
        required: true
        description: 'Дата и время последнего изменения по продаже/возврату. <br>
          Дата в формате RFC3339. Можно передать дату или дату со временем.  Время
          можно указывать с точностью до секунд или миллисекунд. <br> Литера `Z` в
          конце строки означает, что время передается в UTC-часовом поясе. <br> При
          ее отсутствии время считается в часовом поясе Мск (UTC+3). <br>Примеры:
          <ul> <li> `2019-06-20` <li> `2019-06-20T00:00:00Z` <li> `2019-06-20T23:59:59`
          <li> `2019-06-20T00:00:00.12345Z` <li> `2019-06-20T00:00:00.12345` <li>
          `2017-03-25T00:00:00` </ul>

          '
      - $ref: '#/components/parameters/flag'
      responses:
        200:
          description: Список продаж
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SalesItem'
              example:
              - date: '2022-03-04T18:08:31'
                lastChangeDate: '2022-03-06T10:11:07'
                warehouseName: Подольск
                countryName: Россия
                oblastOkrugName: Центральный федеральный округ
                regionName: Московская
                supplierArticle: '12345'
                nmId: 1234567
                barcode: '123453559000'
                category: Бытовая техника
                subject: Мультистайлеры
                brand: Тест
                techSize: '0'
                incomeID: 56735459
                isSupply: false
                isRealization: true
                totalPrice: 1887
                discountPercent: 18
                spp: 26
                forPay: 1284.01
                finishedPrice: 1145
                priceWithDisc: 1547
                saleID: S9993700024
                orderType: Клиентский
                sticker: '926912515'
                gNumber: '34343462218572569531'
                odid: 1003837147757
                srid: 11.rf9ef11fce1684117b0nhj96222982382.3.0
        400:
          description: Ошибка в запросе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseErrorStatistics'
              examples:
                CantParseDateFrom:
                  $ref: '#/components/examples/CantParseDateFrom'
        401:
          description: Не авторизован
          content:
            application/json:
              schema:
                type: string
              examples:
                TokenMissing:
                  $ref: '#/components/examples/TokenMissing'
                TokenInvalid:
                  $ref: '#/components/examples/TokenInvalid'
                TokenIsNotApplicable:
                  $ref: '#/components/examples/TokenIsNotApplicable'
                TokenNotFound:
                  $ref: '#/components/examples/TokenNotFound'
        429:
          description: Слишком много запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response429'
              examples:
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
  /api/v1/supplier/reportDetailByPeriod:
    servers:
    - url: https://statistics-api.wildberries.ru/
    get:
      security:
      - HeaderApiKey: []
      summary: Отчет о продажах по реализации
      description: 'Детализация к отчету реализации.  <br> В отчете доступны данные
        за последние 3 месяца. <br> В случае отсутствия данных за указанный период
        метод вернет `null`. <br> Технический перерыв в работе метода: каждый понедельник
        с 3:00 до 16:00. <br> <a href="../../excel_save/ru/index.html">Инструкция:
        Сохранение статистики в Excel</a>

        '
      tags:
      - Статистика
      parameters:
      - name: dateFrom
        in: query
        schema:
          type: string
          format: RFC3339
        required: true
        description: 'Начальная дата отчета.<br> Дата в формате RFC3339. Можно передать
          дату или дату со временем.  Время можно указывать с точностью до секунд
          или миллисекунд. <br> Литера `Z` в конце строки означает, что время передается
          в UTC-часовом поясе. <br> При ее отсутствии время считается в часовом поясе
          Мск (UTC+3). <br>Примеры: <ul> <li> `2019-06-20` <li> `2019-06-20T00:00:00Z`
          <li> `2019-06-20T23:59:59` <li> `2019-06-20T00:00:00.12345Z` <li> `2019-06-20T00:00:00.12345`
          <li> `2017-03-25T00:00:00` </ul>

          '
      - in: query
        name: limit
        schema:
          type: integer
          default: 100000
        required: false
        description: Максимальное количество строк отчета, возвращаемых методом. Не
          может быть более 100000.
      - in: query
        name: dateTo
        schema:
          type: string
          format: date
        required: true
        description: Конечная дата отчета
      - in: query
        name: rrdid
        schema:
          type: integer
        required: false
        description: "Уникальный идентификатор строки отчета. Необходим для получения\
          \ отчета частями. \n<br>\nЗагрузку отчета нужно начинать с `rrdid = 0` и\
          \ при последующих вызовах API передавать в запросе значение `rrd_id` из\
          \ последней строки, полученной в результате предыдущего вызова. \n<br>\n\
          Таким образом для загрузки одного отчета может понадобиться вызывать API\
          \ до тех пор, пока количество возвращаемых строк не станет равным нулю.\n"
      responses:
        200:
          description: Список реализованных позиций
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DetailReportItem'
        401:
          description: Не авторизован
          content:
            application/json:
              schema:
                type: string
              examples:
                TokenMissing:
                  $ref: '#/components/examples/TokenMissing'
                TokenInvalid:
                  $ref: '#/components/examples/TokenInvalid'
                TokenIsNotApplicable:
                  $ref: '#/components/examples/TokenIsNotApplicable'
                TokenNotFound:
                  $ref: '#/components/examples/TokenNotFound'
        429:
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: string
                - $ref: '#/components/schemas/Response429'
              examples:
                TechnicalBreak:
                  value: 'Технический перерыв в работе метода: каждый понедельник
                    с 3:00 до 16:00.'
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
